version: 2.1

jobs:
  tests: 
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - run:
          name: Run tests and coverage
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install -r requirements.txt
            python3 -m pip install coverage
            coverage run manage.py test -v 3
            coverage report -m



workflows:
  unitracker: 
    jobs:
      - tests:
        filters:
          branches:
            only:
              - main
