version: 2.1

jobs:
  tests: 
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python3 -m pip install -r requirements.txt
            python3 manage.py test -v 3


workflows:
  unitracker: 
    jobs:
      - tests:
        filters:
          branches:
            only:
              - main
