version: 2.1

jobs:
  api-test: 
    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python3 -m pip install -r requirements.txt
            python3 manage.py test api


workflows:
  unitracker-api: 
    jobs:
      - api-test
