# Generated by Django 3.2.9 on 2021-11-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
